apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-16T11:07:53Z"
  generation: 2
  labels:
    app: prime1
  name: prime1
  namespace: default
  resourceVersion: "17015"
  selfLink: /apis/apps/v1/namespaces/default/deployments/prime1
  uid: be631370-214d-4875-9034-39b9d34a20a1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prime1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prime1
    spec:
      containers:
      - image: asia.gcr.io/primefactor1/prime1
        imagePullPolicy: Always
        name: prime1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-11-16T11:07:53Z"
    lastUpdateTime: "2020-11-16T11:07:53Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-11-16T11:29:20Z"
    lastUpdateTime: "2020-11-16T11:29:20Z"
    message: ReplicaSet "prime1-558b4c4954" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
