apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2020-11-16T11:13:41Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: prime1
  name: prime1-service
  namespace: default
  resourceVersion: "11285"
  selfLink: /api/v1/namespaces/default/services/prime1-service
  uid: a1524d33-5d3a-4ccb-bc4a-1db86cb159e7
spec:
  clusterIP: 10.108.11.154
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30362
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: prime1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.85.2.79
